### ISSUE TITLE
Link with GNS3 VM

### ISSUE THREAD

**Issue by cadouko** [jsimonetti/docker-gns3-server#3]
In the preferences, impossible to make communicate gns3 with vmware to load IOS to GNS3 VM. Do you have a procedure?

**Comment by jsimonetti** [comment]
Hi, i am uncertain if it will even be possible to make the gns3 server from the container talk to a vmware server. I also have no need for that, so have not tried. It could very well be firewalling from docker that prevents them to communicate together.
If you happen to get this working I would appreciate a headsup for documentation purposes.
For now Ill close this issue since I have no use for it.
